- name : Variables from files
  hosts: local
  #connect: local
  vars_files:
    - vars.yaml
  tasks:
    - name: Print variables from files
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ COURSE }}, Duration is {{ DURATION }} Hrs, Trainer is {{ TRAINER }}"