#  ansible-playbook -i inventory.ini 09-vars-from-args.yaml -e "COURSE='DevOps with AWS' DURATION=120 TRAINER='Siva Kumar'"
- name: Printing variables from command line arguments
  hosts: local
  tasks:
  - name: Print command line argument variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ COURSE }} from Trainer {{ TRAINER }} and course duration is {{ DURATION }} Hours"