- name: Conditions in Ansible
  hosts: local
  vars_prompt:
    - name: My_number
      prompt: Please enter the number
      private: false
  tasks:
  - name: Verify if the number is greater than 10
    ansible.builtin.debug:
      msg: "Given number {{ My_number }} is greater than 10"
    when: My_number > 10
    ignore_errors: True

  - name: Verify if the number is less than 10
    ansible.builtin.debug:
      msg: "Given number {{ My_number }} is greater than 10"
    when: My_number < 10
    ignore_errors: True