- name: Gather facts and write the output to a file
  hosts: local
  become: yes
  tasks:
    - name: Gather facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Gather facts ans store data
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: /home/ec2-user/ansible/facts.json
        mode: '0777'