- name: Install all the packages in the loop
  hosts: web
  become: yes
  tasks:
  - name: Install packages in the loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: # mention package names
      - nginx
      - mysql
      - postfix
      - httpd
